import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { Writable } from 'stream';

interface OrderData {
  orderId: string;
  productName: string;
  sellerName: string;
  amount: number;
  currency: string;
  paymentMethod: string;
  customerName: string;
  customerEmail: string;
  estimatedDelivery: Date;
  confidenceScore: number;
  createdAt: Date;
}

interface LedgerData {
  eventType: string;
  description: string;
  timestamp: Date;
  verifiedBy: string;
  verificationHash: string;
}

export async function generateLedgerPDF(
  order: OrderData,
  entries: LedgerData[],
  orderUrl: string,
  output: Writable
): Promise<void> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(output);

  // Generate QR code as data URL
  const qrDataUrl = await QRCode.toDataURL(orderUrl, { width: 120, margin: 1 });
  const qrBuffer = Buffer.from(qrDataUrl.split(',')[1], 'base64');

  // Colors
  const primary = '#6C63FF';
  const dark = '#1a1a2e';
  const grey = '#6b7280';
  const green = '#10B981';

  // Header
  doc.fontSize(24).fillColor(primary).text('🛡️ ORDRA', 50, 50);
  doc.fontSize(10).fillColor(grey).text('Post-Purchase Trust System', 50, 80);
  doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

  // Title
  doc.fontSize(18).fillColor(dark).text('Order Assurance Ledger™', 50, 120);
  doc.fontSize(10).fillColor(grey).text(
    'A signed digital proof of every verification event on this order.',
    50, 145
  );

  // Order Details Box
  const boxY = 175;
  doc.roundedRect(50, boxY, 495, 130, 8).fillColor('#f8f9ff').fill();
  doc.fillColor(dark);

  const col1 = 65; const col2 = 300;
  let y = boxY + 15;

  doc.fontSize(9).fillColor(grey).text('Order ID', col1, y);
  doc.fontSize(10).fillColor(dark).text(order.orderId, col1, y + 12);

  doc.fontSize(9).fillColor(grey).text('Customer', col2, y);
  doc.fontSize(10).fillColor(dark).text(order.customerName, col2, y + 12);

  y += 35;
  doc.fontSize(9).fillColor(grey).text('Product', col1, y);
  doc.fontSize(10).fillColor(dark).text(order.productName.slice(0, 45), col1, y + 12);

  doc.fontSize(9).fillColor(grey).text('Seller', col2, y);
  doc.fontSize(10).fillColor(dark).text(order.sellerName, col2, y + 12);

  y += 35;
  const amountStr = `₹${order.amount.toLocaleString('en-IN')}`;
  doc.fontSize(9).fillColor(grey).text('Amount', col1, y);
  doc.fontSize(10).fillColor(dark).text(amountStr, col1, y + 12);

  doc.fontSize(9).fillColor(grey).text('Payment', col2, y);
  doc.fontSize(10).fillColor(dark).text(order.paymentMethod, col2, y + 12);

  // Confidence Score
  y = boxY + 130 + 20;
  doc.fontSize(9).fillColor(grey).text('Confidence Score', 50, y);
  doc.fontSize(16).fillColor(green).text(`${order.confidenceScore}%`, 50, y + 14);

  doc.fontSize(9).fillColor(grey).text('Estimated Delivery', 200, y);
  doc.fontSize(10).fillColor(dark).text(
    order.estimatedDelivery.toLocaleDateString('en-IN', {
      weekday: 'short', year: 'numeric', month: 'short', day: 'numeric'
    }),
    200, y + 14
  );

  // QR Code
  doc.image(qrBuffer, 440, y - 10, { width: 80, height: 80 });
  doc.fontSize(7).fillColor(grey).text('Scan to verify', 453, y + 72);

  // Ledger Entries
  y += 60;
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e5e7eb').stroke();
  y += 15;
  doc.fontSize(14).fillColor(dark).text('Verification Ledger', 50, y);
  y += 25;

  for (const entry of entries) {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    // Green dot
    doc.circle(62, y + 6, 4).fillColor(green).fill();

    doc.fontSize(10).fillColor(dark).text(entry.eventType, 75, y);
    doc.fontSize(8).fillColor(grey).text(entry.description, 75, y + 14);

    const timeStr = entry.timestamp.toLocaleString('en-IN', {
      hour: '2-digit', minute: '2-digit', hour12: true,
      day: '2-digit', month: 'short',
    });
    doc.fontSize(8).fillColor(grey).text(
      `${timeStr} · Verified by ${entry.verifiedBy}`,
      75, y + 26
    );
    doc.fontSize(7).fillColor('#9ca3af').text(`Hash: ${entry.verificationHash}`, 75, y + 38);

    y += 55;
  }

  // Footer
  y = Math.max(y + 20, 700);
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e5e7eb').stroke();
  doc.fontSize(8).fillColor(grey).text(
    `Generated by Ordra · ${new Date().toLocaleString('en-IN')} · This document is digitally verified.`,
    50, y + 10, { align: 'center' }
  );

  doc.end();
}
